# ======================================================
# TRIGGERS
# ======================================================

trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

# ======================================================
# AGENT POOL
# ======================================================

pool:
  name: WindowsSelfHostedPool

# ======================================================
# VARIABLES
# ======================================================

variables:
  nodeVersion: '18.x'

# ======================================================
# STAGES
# ======================================================

stages:
- stage: Build
  displayName: Build_and_Test
  jobs:
    - job: BuildJob
      displayName: Build_Job
      steps:
        - checkout: self

        - task: NodeTool@0
          displayName: Use_NodeJS
          inputs:
            versionSpec: $(nodeVersion)

        - task: CmdLine@2
          displayName: Install_Build_Test
          inputs:
            workingDirectory: $(System.DefaultWorkingDirectory)
            script: |
              npm install
              npm run build
              npm test